name: Create PR

on: repository_dispatch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Update submodule
      run: |
        git submodule foreach git pull origin master
        git add .
        git commit -m "update submodule"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: this is title
        body: this is body