name: Create PR

on: repository_dispatch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup git
      run: |
        git config --global user.name yykaoruko
        git config --global user.email yykaoruko@gmail.com

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout
      run: |
        git checkout -b feature/submodule

    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: yykaoruko/my-log
        token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        path: app/contents/logs

    - name: Git commit
      run: |
        git add .
        git commit -m 'chore: update submodule'
        git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'feature/submodule'
        force: true

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        curl -X POST
        -H "Authorization: token ${GITHUB_TOKEN}"
        -H "Accept: application/vnd.github.everest-preview+json"
        -d "{\"title\": \"update submodule\", \"head\": \"feature/submodule\", \"base\": \"master\"}"
        "https://api.github.com/repos/yykaoruko/rukolog/pulls"
