name: Create PR

on: repository_dispatch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup git
      run: |
        # git init
        git config --global user.name yykaoruko
        git config --global user.email yykaoruko@gmail.com

    # - name: Checkout master
    #   env:
    #     GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    #   run: |
    #     git clone https://yykaoruko:${GITHUB_ACCESS_TOKEN}@github.com/yykaoruko/rukolog.git
    #     cd rukolog

    # - name: Checkout branch
    #   run: git checkout -b feature/submodule

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: feature/submodule

    - name: Update submodule
      run: |
        pwd
        ls al
        # git submodule update -i
        # git submodule foreach git pull origin master
        # git status

    # - name: Checkout submodule
    #   uses: actions/checkout@v2
    #   with:
    #     repository: yykaoruko/my-log
    #     token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    #     path: app/contents/logs

    - name: Git commit
      run: |
        git status
        # git add .
        # git commit -m 'update submodule'
        # git status

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'feature/submodule'
        force: true

    - name: Create Pull Request
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      run: >
        curl -X POST
        -H "Authorization: token ${GITHUB_ACCESS_TOKEN}"
        -H "Accept: application/vnd.github.everest-preview+json"
        -d "{\"title\": \"update submodule\", \"head\": \"feature/submodule\", \"base\": \"master\"}"
        "https://api.github.com/repos/yykaoruko/rukolog/pulls"
